# Generated by Django 5.2 on 2025-05-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', '等待中'), ('accepted', '已接受'), ('rejected', '已拒絕')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', '追蹤'), ('follow_request_received', '收到追蹤請求'), ('follow_request_sent', '發送追蹤請求'), ('follow_accepted', '追蹤已接受'), ('like', '按讚'), ('comment', '留言')], max_length=25),
        ),
    ]
