# Generated by Django 5.2 on 2025-05-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_remove_user_following_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='技能名稱')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='分類')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='圖標')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='顯示名稱'),
        ),
        migrations.AddField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='個人標題'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_follower_count',
            field=models.BooleanField(default=True, verbose_name='顯示追蹤者數量'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_color',
            field=models.CharField(default='#1a73e8', max_length=20, verbose_name='主題顏色'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='個人網站'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.skill'),
        ),
    ]
