# Generated by Django 5.2 on 2025-05-08 04:07

import apps.portfolios.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_remove_portfolio_link_portfolio_demo_url_and_more'),
        ('users', '0005_skill_user_display_name_user_headline_user_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='圖標代碼')),
            ],
            options={
                'verbose_name': '作品集分類',
                'verbose_name_plural': '作品集分類',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': '作品集', 'verbose_name_plural': '作品集'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='video',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='app_store_url',
            field=models.URLField(blank=True, null=True, verbose_name='App Store連結'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='建議尺寸：1200x630，將在個人檔案頁面顯示', null=True, upload_to='portfolio_covers/', verbose_name='封面圖片'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='google_play_url',
            field=models.URLField(blank=True, null=True, verbose_name='Google Play連結'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='設為特色作品將會在個人資料頁優先顯示', verbose_name='特色作品'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='點讚次數'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='項目結束日期'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='項目開始日期'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills_used',
            field=models.ManyToManyField(blank=True, related_name='used_in_portfolios', to='users.skill', verbose_name='使用的技能'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='簡短摘要'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='瀏覽次數'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='demo_url',
            field=models.URLField(blank=True, null=True, verbose_name='示範連結'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub連結'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=255, verbose_name='標題'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='用戶'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube連結'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='portfolios.portfoliocategory', verbose_name='分類'),
        ),
        migrations.CreateModel(
            name='PortfolioComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='評論內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolios.portfolio', verbose_name='作品集')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '作品集評論',
                'verbose_name_plural': '作品集評論',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='portfolio_media/', validators=[apps.portfolios.models.validate_file_extension], verbose_name='媒體文件')),
                ('media_type', models.CharField(choices=[('image', '圖片'), ('video', '影片')], max_length=10, verbose_name='媒體類型')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='標題')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portfolios.portfolio', verbose_name='作品集')),
            ],
            options={
                'verbose_name': '作品集媒體',
                'verbose_name_plural': '作品集媒體',
                'ordering': ['portfolio', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='portfolios.portfolio', verbose_name='作品集')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '作品集點讚',
                'verbose_name_plural': '作品集點讚',
                'unique_together': {('portfolio', 'user')},
            },
        ),
    ]
