# Generated by Django 5.2 on 2025-05-06 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='程式碼')),
                ('language', models.CharField(max_length=50, verbose_name='程式語言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_blocks', to='posts.post', verbose_name='貼文')),
            ],
            options={
                'verbose_name': '程式碼區塊',
                'verbose_name_plural': '程式碼區塊',
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_media/', verbose_name='檔案')),
                ('file_type', models.CharField(choices=[('image', '圖片'), ('video', '影片')], max_length=10, verbose_name='檔案類型')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post', verbose_name='貼文')),
            ],
            options={
                'verbose_name': '貼文多媒體',
                'verbose_name_plural': '貼文多媒體',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
